"""
External Resource Discovery: real internet search via DuckDuckGo (ddgs).

Format-aware query building so results aren't biased toward any one content
type, plus deterministic query VARIATION so a learner who has already seen
the obvious results gets genuinely different ones next time.

The query templates are a fixed, ordered list -- not generated by an LLM.
Same topic + same seen-set always produces the same query sequence, so every
recommendation stays reproducible and explainable.

Install: pip install ddgs
"""

from ddgs import DDGS

from src.agents.recommendation_system.models.resource import Resource
from src.agents.recommendation_system.verification.domain_policy import is_blocked

MAX_DISCOVERY_RESULTS = 5
RESULTS_PER_QUERY = 10

FORMAT_SEARCH_TERMS = {
    "video": "video",
    "article": "article",
    "course": "online course",
    "book": "book",
    "tutorial": "tutorial",
    "documentation": "official documentation",
    "research_paper": "research paper",
    "practice_platform": "practice problems",
}

# Tried in order. {topic}, {level} and {format} are filled in per request.
# Earlier templates are the most direct; later ones deliberately reach for
# different corners of the web so an exhausted learner gets new material.
QUERY_TEMPLATES = [
    "{topic} {level} {format}",
    "learn {topic} from scratch {format}",
    "{topic} crash course {format}",
    "best {format} to learn {topic}",
    "{topic} explained step by step {format}",
    "{topic} full guide {format}",
]


def build_query(template, search_requirement):
    """Fills one template and tidies up the spacing.

    Missing values become empty strings rather than the word 'None', and
    repeated spaces are collapsed, so a partial learner profile still
    produces a clean query.
    """
    topic = search_requirement["topic"] or ""
    level = search_requirement["level"] or ""
    requested_format = search_requirement.get("format")
    format_term = FORMAT_SEARCH_TERMS.get(requested_format, "")

    query = template.format(topic=topic, level=level, format=format_term)
    return " ".join(query.split())


def search_once(query, max_results):
    """Runs one real search. Returns raw result dicts, or [] on any failure."""
    try:
        with DDGS() as search_engine:
            return list(search_engine.text(query, max_results=max_results))
    except Exception as error:
        print(f"[resource discovery] Search failed for {query!r} ({error}).")
        return []


def discover_resources(search_requirement, exclude_urls=None, max_results=MAX_DISCOVERY_RESULTS):
    """Searches the real internet, skipping anything in exclude_urls.

    Works through QUERY_TEMPLATES in order, stopping as soon as enough NEW
    candidates have been collected. Blocked domains are dropped here, before
    any network verification is paid for.

    IMPORTANT: format is left as None, NOT set to the format we searched for.
    Searching for videos does not make every result a video -- search engines
    return playlists, category pages, and articles about videos. Claiming a
    format we have not verified would hand out 30 unearned scoring points.
    resource_analyzer.py determines the real format from the URL afterwards.
    """
    topic = search_requirement["topic"]
    if topic is None:
        return []

    if exclude_urls is None:
        exclude_urls = set()

    discovered = []
    collected_urls = set()

    for template_number, template in enumerate(QUERY_TEMPLATES, start=1):
        if len(discovered) >= max_results:
            break

        query = build_query(template, search_requirement)
        results = search_once(query, RESULTS_PER_QUERY)

        new_this_round = 0
        blocked_this_round = 0

        for result in results:
            url = result.get("href", "")
            if not url or url in exclude_urls or url in collected_urls:
                continue

            # Free check -- do it before anything expensive touches this url.
            if is_blocked(url):
                blocked_this_round += 1
                collected_urls.add(url)
                continue

            discovered.append(
                Resource(
                    title=result.get("title", ""),
                    url=url,
                    description=result.get("body", ""),
                    topic=topic,
                    difficulty=None,
                    format=None,
                    duration=None,
                )
            )
            collected_urls.add(url)
            new_this_round += 1

            if len(discovered) >= max_results:
                break

        print(
            f"[resource discovery] Query {template_number} {query!r}: "
            f"{new_this_round} new, {blocked_this_round} blocked "
            f"(total {len(discovered)}/{max_results})."
        )

    return discovered